-- Your SQL goes here
CREATE TABLE IF NOT EXISTS 'clinics'(
    'id' INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    'name' VARCHAR(255) UNIQUE NOT NULL,
    'plato_code' VARCHAR(255) UNIQUE NOT NULL,
    'is_online' BOOLEAN DEFAULT FALSE,
    'availability_time' VARCHAR(255) NOT NULL,
    'is_archived' BOOLEAN DEFAULT FALSE,
    'archived_at' TIMESTAMP DEFAULT NULL,
    'created_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    'updated_at' TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);