services:
  hello-world:
    build:
      context: ./hello-world
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8081:8081"
    networks:
      - rust-net
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - rust-net

networks:
  rust-net:
    driver: bridge