-- CREATE TABLE users (
--     id SERIAL PRIMARY KEY,
--     first_name VARCHAR NOT NULL,
--     last_name VARCHAR,
--     email VARCHAR UNIQUE NOT NULL,
--     is_regular BOOLEAN DEFAULT TRUE,
--     is_doctor BOOLEAN DEFAULT FALSE,
--     ops_team BOOLEAN DEFAULT FALSE,
--     email_verified_at TIMESTAMP,
--     password VARCHAR,
--     google_id VARCHAR,
--     apple_id VARCHAR,
--     remember_token VARCHAR,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     rbac_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid() 
-- );

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR,
    email VARCHAR UNIQUE NOT NULL,
    is_regular BOOLEAN DEFAULT TRUE,
    is_doctor BOOLEAN DEFAULT FALSE,
    ops_team BOOLEAN DEFAULT FALSE,
    email_verified_at TIMESTAMP,
    password VARCHAR,
    google_id VARCHAR,
    apple_id VARCHAR,
    remember_token VARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    speciality_id BIGINT,
    image VARCHAR,
    is_profile_filled BOOLEAN DEFAULT FALSE NOT NULL,
    is_health_info_filled BOOLEAN DEFAULT FALSE NOT NULL,
    dob DATE,
    sex INTEGER,
    mobile_number VARCHAR,
    address TEXT,
    city_id BIGINT,
    profile_picture VARCHAR,
    on_regular_medication_status BOOLEAN DEFAULT TRUE NOT NULL,
    medications TEXT,
    info_sources JSON,
    profile_email VARCHAR,
    title VARCHAR,
    speciality_title VARCHAR,
    sub_speciality_title VARCHAR,
    plato_code VARCHAR,
    plato_id VARCHAR,
    is_consent_approved BOOLEAN DEFAULT FALSE NOT NULL,
    occupation VARCHAR,
    app_rating DOUBLE PRECISION,
    app_rating_description TEXT,
    shopify_id VARCHAR,
    xendit_id VARCHAR,
    device_name VARCHAR,
    app_version VARCHAR,
    rbac_id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid() 
);

SELECT diesel_manage_updated_at('users');